### ISSUE TITLE
System information -Xmx value is blank when -Xmx does not have units

### ISSUE THREAD

**Issue by kkazmierczyk** [IBM/javacore-analyser#17]
If the Xmx tag in the javacore has a format of
123445
without the unit, parsing will fail.
This is because the parse_mem_arg method of javacore set assumes there will be a unit

**Comment by PiotrAniola82** [comment]
If the Xmx tag in the javacore has a format of
123445
without the unit, parsing will fail.
This is because the parse_mem_arg method of javacore set assumes there will be a unit
