### ISSUE TITLE
28-simplyfy-web

### ISSUE THREAD

**Issue by PiotrAniola82** [IBM/javacore-analyser#28]
In the webapp, the report name should be optional and default to:
- filename + generation time for archive files
- "javacores" + generation time for individual javacores

**Comment by kkazmierczyk** [comment]
I changed the title. Here is my proposed change:

<img width="797" alt="image" src="https://github.com/user-attachments/assets/7f3bcb17-a7ef-4632-a8b6-1065c56dfb24">

@PiotrAniola82 @tjanasiewicz  any comments on this?
