### ISSUE TITLE
Correct messages when running help application

### ISSUE THREAD

**Issue by kkazmierczyk** [IBM/javacore-analyser#39]
When you run javacore analyser with -h option, the description could be better. Here is the current description:
```
usage: javacore_analyser_batch [-h] [--separator SEPARATOR] input_param output_param

positional arguments:
  input_param           Input file(s) or directory
  output_param          Report output directory

options:
  -h, --help            show this help message and exit
  --separator SEPARATOR
                        Input files separator (default ";"
```

This task is to improve the messages.

**Comment by kkazmierczyk** [comment]
Assigning to @tjanasiewicz as we were discussing during a call.

**Comment by tjanasiewicz** [comment]
@kkazmierczyk could you please confirm that changes where the above-mentioned description was added have already been delivered? Asking because I am not able to find it in the main:
![image](https://github.com/user-attachments/assets/3606d088-0b38-4249-aa50-37b124a6bc44)

**Comment by kkazmierczyk** [comment]
> @kkazmierczyk could you please confirm that changes where the above-mentioned description was added have already been delivered? Asking because I am not able to find it in the main: ![image](https://private-user-images.githubusercontent.com/46438675/391458171-3606d088-0b38-4249-aa50-37b124a6bc44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMzE2OTIsIm5iZiI6MTczMzEzMTM5MiwicGF0aCI6Ii80NjQzODY3NS8zOTE0NTgxNzEtMzYwNmQwODgtMGIzOC00MjQ5LWFhNTAtMzdiMTI0YTZiYzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA5MjMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZDA3MDMwNTUwYmE1ZWIyOWI2ZDYxZDQzMjU2NTM4MTAyOTllZTQxYzgzYzY3N2M5OWQ0ZGY2Mjc5Yzk3ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TFFDkmrpTFpk84BM1vfDm-DwYgbGOgcrHr4_jztNpRE)

I think you have already managed it.

**Comment by tjanasiewicz** [comment]
@kkazmierczyk yes, and pull request was already created (#63).
