### ISSUE TITLE
Different Time range on GC activity and CPU load graphs

### ISSUE THREAD

**Issue by tjanasiewicz** [IBM/javacore-analyser#71]
**Describe the bug**
Different Time range on GC activity and CPU load graphs

**To Reproduce**
Unknown

**Expected behavior**
The same time range should be shown on both graphs

**Screenshots**

And example:
![image](https://github.com/user-attachments/assets/322d8a15-57da-426f-90be-41f7adaa4d7a)

**Comment by tjanasiewicz** [comment]
There is a chance that this issue is observed when the input data are invalid, but still, the range should be the same, and should consider the first and last javacores collection time.

@PiotrAniola82 any comments?

**Comment by PiotrAniola82** [comment]
CPU chart looks correct.
GC chart should not be displayed if there is no verboseGC data.
If there are no verbose GC logs in the input, there should be a message: "No verbosegc logs"
If there are verbose GC logs, but no collections in the javacore time limits, there should be a message "No GC activity was detected within the javacore time limits"
